### ISSUE TITLE
Command ExtractAPI failed with a nonzero exit code

### ISSUE THREAD

**Issue by knightfork** [philipturner/ARHeadsetKit#90]
Hi Philip, thank you so much for creating a great package/framework! I have been trying to make it work as a framework but it fails with 'Command ExtractAPI failed with a nonzero exit code' and it fails to find metal_stdlib file in the framework - "fatal error: 'metal_stdlib' file not found". I am working with iOS SDK 16.2. Not sure if that's something to do with it. I am new to metal (and to AR) so not quite sure how to fix this issue. I am quite sure I followed the tutorial for 'Reconfiguring ARHeadsetKit' to the T. I tried setting the header paths in the settings but to no avail. What might I be doing wrong?

**Comment by philipturner** [comment]
I made these tutorials over a year ago. There should be some way to make this work - Xcode is just different now. Have you gotten the Xcode framework to compile without using any Metal shaders? Try just copying and pasting the MetalUtilities.h file verbatim, like a file you authored in your own Xcode project.

**Comment by knightfork** [comment]
Would you be able to build it using the latest SDK and confirm if it's working for you? In the meanwhile I'll try your suggestion.

**Comment by philipturner** [comment]
I found the problem. In the Xcode project I see when committing ARHeadsetKit to GitHub, everything is correct. The headers appear under "Headers" in the project build phase. But when I download using Git Submodules, the headers magically migrate to "Compile Sources". I also had to rename them from `.h` to `.h.metal` because the compiler was flagging them as C or C++ files. Use `Cmd + F` and search-replace to rename all of these headers with the new extension. That should update the include macros in your source files and ARHeadsetKit's source files.
- `ARObjectUtilities.h` -> `ARObjectUtilities.h.metal`
- `ColorUtilities.h` -> `ColorUtilities.h.metal`
- `MemoryUtilities.h` -> `MemoryUtilities.h.metal`

Then, manually modify the names of the files themselves. They're located in the `ARHeadsetKit.xcodeproj` reference embedded into your source folder. Go into Project Settings -> TARGETS -> Build Phases -> "Compile Sources", and locate the changed files. They'll be difficult to distinguish from their implementation files, which share the same name but different extensions. The headers are the ones without `Private` in the file path. Drag those into the "Headers" section.

<details><summary>What I see in the cloned GitHub repository:</summary>

<img width="818" alt="Screenshot 2023-03-17 at 3 50 17 PM" src="https://user-images.githubusercontent.com/71743241/226019659-38552c41-9d17-4a5d-9bd0-b6d813e17ddf.png">

</details>
<details><summary>What the embedded submodule originally looks like:</summary>

<img width="949" alt="Screenshot 2023-03-17 at 4 04 23 PM" src="https://user-images.githubusercontent.com/71743241/226021191-48e560b3-f0d9-4fab-8827-3f958d68487d.png">

</details>
<details><summary>What I changed the submodule to:</summary>

<img width="968" alt="Screenshot 2023-03-17 at 3 50 41 PM" src="https://user-images.githubusercontent.com/71743241/226019720-fcd9f68b-21ba-46ad-a325-e03c50b88d49.png">

</details>

I don't think there's a seamless way to fix this problem, but I'll hyperlink this GitHub issue into the relevant tutorial. It might be a bug in Xcode.

**Comment by knightfork** [comment]
Builds perfect now!!

Great job catching the problem and thanks once again for your assistance Philip!

**Comment by knightfork** [comment]
Is there a way to keep in touch with you via email while I experiment with the framework? Please send me an email if you are okay.

I would understand if you are not comfortable communicating via email.

EDIT: We are now connected but we will keep the framework related questions in public domain.

**Comment by philipturner** [comment]
I copied the contents of the comment into a private Google Doc. I prefer to discuss over public if possible, just to make stuff reproducible. But if you are more comfortable discussing over email (e.g. privacy reasons), I can do that too.
